global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'telephony-gateway'
    static_configs:
      - targets: ['telephony-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'asr-service'
    static_configs:
      - targets: ['asr-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'tts-service'
    static_configs:
      - targets: ['tts-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'dialog-orchestrator'
    static_configs:
      - targets: ['dialog-orchestrator:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'rag-service'
    static_configs:
      - targets: ['rag-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'crm-connector'
    static_configs:
      - targets: ['crm-connector:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'admin-api'
    static_configs:
      - targets: ['admin-api:8007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s
