receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 400
    spike_limit_mib: 100
    check_interval: 5s

  attributes:
    actions:
      - key: service.name
        value: sales-voice-assistant
        action: insert

  resource:
    attributes:
      - key: service.name
        value: sales-voice-assistant
        action: upsert
      - key: service.version
        value: "1.0.0"
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

exporters:
  logging:
    loglevel: info

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      service: sales-voice-assistant

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  otlp:
    endpoint: http://jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes, resource, batch]
      exporters: [jaeger, otlp, logging]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, attributes, resource, batch]
      exporters: [prometheus, otlp, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, attributes, resource, batch]
      exporters: [logging]

  extensions: []
